### ISSUE TITLE
Stable set contains linked nodes

### ISSUE THREAD

**Issue by alberto-santini** [heldstephan/exactcolors#1]
Hi Stephan. I setup a toy project [mwss_test](https://github.com/alberto-santini/mwss_test) that uses your library. It seems, however, that the stable set I receive with `call_max_wstable` is invalid, as it contains nodes which are linked by edges.

I am inclined to think the error is in my usage of the library and not in the library itself, but I open this ticket, in case you want to investigate the issue.

**Comment by heldstephan** [comment]
Hi Alberto,

first note that  mwis_sewell/mwss_ext.h contains the "external" API.

You are using more low level functions, which are less documented, but that's fine.
Your code is almost right. It's only the extraction of the result that needs to be fixed.
You are extracting with the following code:
 for(auto i = 1u; i <= n_nodes; i++) {
        if(m_data.best_sol[i] != NULL) {
            stable_set.push_back(m_data.best_sol[i]->name - 1);
        }
    }
You must only use the first  m_data.n_best entries from that array.
Subsequent entries may be filled with deprecated vertices from preliminary lighter stable set solution.
I.e. you code should look like this:

for(auto i = 1u; i <= m_data.n_best; i++) {
       stable_set.push_back(m_data.best_sol[i]->name -1);
}

Please let me know if you still encounter errors.

Best regards,

Stephan
